spring:
  datasource:
    url: jdbc:mysql://mysql.shinigami.io:3306/oauth
    username: oauth
    password: oauth
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: native
  thymeleaf:
    cache: false
error:
  whitelabel:
    enabled: false

jdbc:
  driver: org.sqlite.JDBC