spring.profiles.active: native

server:
  display-name: CloudConfigServer
  port: 8761

security:
  basic:
    enabled: false
  user:
      name: ${VCONFIGUSER:config}
      password: ${VCONFIGPASSWORD:password}

management:
  context-path: /admin
  address: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}
  security:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${VCONFIGUSER:config}:${VCONFIGPASSWORD:password}@${VCONFIGHOST:${HOSTNAME:localhost.shinigami.io}}:${VCONFIGPORT:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false
  instance:
    instanceId: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}:${spring.application.name}:${spring.application.instance_id:${server.port}
    hostname: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}
    non-secure-port: ${spring.application.instance_id:${server.port}}
    secure-port: ${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 5

spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        prefix: /config
        git:
          uri: file:///opt/github/MicroDocker/spring-config
---
spring:
  profiles: native
  
  cloud:
    config:
      server:
        native: 
          search-locations: classpath:/spring-config
---
spring:
  profiles: local
  
  cloud:
    config:
      server:
        git:
          uri: file:///opt/github/MicroDocker/spring-config

---
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/amitkshirsagar13/spring-config.git